# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  terraform {
    backend "azurerm" {
      resource_group_name = "example-rg-name"
      storage_account_name = "saexamplename"
      container_name = "examplecontainername"
      key = "stack1/terraform.tfstate"
    }
  }
