# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  terraform {
  required_version = "~>1.8"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.1.0"
    }
    azapi = {
      source  = "Azure/azapi"
      version = "1.15.0"
    }
    acme = {
      source  = "vancluever/acme"
      version = "2.26.0"
    }
  }
  }

  provider "azurerm" {
  subscription_id = "9d39a7ed-ade3-48a7-b015-5490cae4f9c5"
  features {}
  }
